app:
  publishers:
    sample:
      topics:
        local: sample-local-topic
        dev: sample-dev-topic
        test: sample-test-topic
      pathToId: transaction.id
    payment:
      topics:
        local: sample-payment-local
        dev: sample-payment-dev
        test: sample-payment-test
      pathToId: paymentId

  # brokers mapping allows specifying external bootstrap servers per env key
  brokers:
    # for local we will use the embedded broker provided by this app (leave blank or set to special value 'embedded')
    local: embedded
    # examples for external brokers - replace with your real bootstrap servers when targeting dev/test
    dev: localhost:9093
    test: localhost:9094


server:
  port: 8082
# server port removed because this app runs as a desktop UI embedded in Spring Boot
spring:
  main:
    allow-bean-definition-overriding: true
